accounts:
  - name: michael
    coins: ["10000000nom"]
  - name: charles
    coins: ["10000000nom"]
  - name: spout
    coins: ["10000000nom"]
build:
  binary: "onomyd"
validator:
  name: charles
  staked: "10000000nom"
client:
  vuex:
    path: "vue/src/store"
faucet:
  name: spout
  coins: ["10nom"]
  coins_max: ["1000nom"]
  port: 4500
init:
  keyring-backend: "os"
host:
  rpc: ":26657"
  p2p: ":26658"
  prof: ":6061"
  grpc: ":9091"
  api: ":1317"
  frontend: ":80"
  dev-ui: ":12346"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "nom"