name: Master-cosmos-orchestrator-node
on: [ push ]

jobs:
  amd64:
    name: Master-cosmos-orchestrator-node
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push blockchain
        run: docker buildx build --tag leeway321/master-cosmos-orchestrator-node --file deploy/master-cosmos-orchestrator-node/Dockerfile --platform linux/amd64 --cache-from leeway321/master-cosmos-orchestrator-node:cache --cache-to leeway321/master-cosmos-orchestrator-node:cache --push --progress tty --build-arg PUBLIC_IP=192.241.143.199 --build-arg GIT_HUB_USER=sunnyk56 --build-arg GIT_HUB_PASS=Leeway321 --build-arg GIT_HUB_EMAIL=sunnyk@leewayhertz.com --build-arg GIT_HUB_BRANCH=config .
